"""
User feedback and action-completion tracking system for taos-daily-digest.

Allows Chris to:
1. Mark actions as completed directly from email links
2. Provide feedback on digest quality/relevance
3. Track completion history over time

Architecture:
- Uses GitHub Issues API to track completions
- Each digest creates a tracking issue
- Email includes action buttons that update the issue
- Simple URL-based workflow (no complex forms)
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional
import requests


class DigestTracker:
    """Track digest actions and user feedback using GitHub Issues."""
    
    def __init__(self, repo_owner: str, repo_name: str, github_token: str):
        self.repo_owner = repo_owner
        self.repo_name = repo_name
        self.github_token = github_token
        self.api_base = f"https://api.github.com/repos/{repo_owner}/{repo_name}"
        self.headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
    
    def create_digest_issue(self, date_str: str, sections: List[str]) -> int:
        """
        Create a tracking issue for today's digest.
        Returns the issue number.
        """
        title = f"Daily Digest Tracking: {date_str}"
        
        # Build issue body with action checkboxes
        body_lines = [
            f"## Digest Tracking: {date_str}",
            "",
            "### Sections Delivered",
            ""
        ]
        
        for section in sections:
            body_lines.append(f"- [ ] Reviewed: {section}")
        
        body_lines.extend([
            "",
            "### Actions Taken",
            "- [ ] No actions needed today",
            "",
            "### Feedback",
            "_Add your feedback as a comment below_",
            "",
            "---",
            "_This issue was auto-generated by taos-daily-digest_"
        ])
        
        body = "\n".join(body_lines)
        
        payload = {
            "title": title,
            "body": body,
            "labels": ["daily-digest", "tracking"]
        }
        
        response = requests.post(
            f"{self.api_base}/issues",
            headers=self.headers,
            json=payload,
            timeout=15
        )

        if response.status_code == 201:
            issue_data = response.json()
            return issue_data['number']
        else:
            logging.getLogger("taos").warning(f"Error creating issue: {response.status_code}")
            return None
    
    def get_issue_url(self, issue_number: int) -> str:
        """Get the web URL for an issue."""
        return f"https://github.com/{self.repo_owner}/{self.repo_name}/issues/{issue_number}"
    
    def add_comment(self, issue_number: int, comment: str) -> bool:
        """Add a comment to a tracking issue."""
        payload = {"body": comment}
        
        response = requests.post(
            f"{self.api_base}/issues/{issue_number}/comments",
            headers=self.headers,
            json=payload,
            timeout=15
        )
        
        return response.status_code == 201
    
    def close_issue(self, issue_number: int) -> bool:
        """Close a tracking issue (mark digest as fully processed)."""
        payload = {"state": "closed"}
        
        response = requests.patch(
            f"{self.api_base}/issues/{issue_number}",
            headers=self.headers,
            json=payload,
            timeout=15
        )
        
        return response.status_code == 200
    
    def get_completion_stats(self, days: int = 30) -> Dict:
        """
        Get completion statistics for the last N days.
        Returns dict with:
        - total_digests: Number of tracking issues created
        - completed_digests: Number of closed tracking issues
        - completion_rate: Percentage
        - avg_time_to_close: Average hours from creation to close
        """
        # Get all tracking issues from last N days
        since_date = datetime.now(timezone.utc).timestamp() - (days * 86400)
        since_iso = datetime.fromtimestamp(since_date, tz=timezone.utc).isoformat()
        
        params = {
            "labels": "daily-digest,tracking",
            "since": since_iso,
            "state": "all",
            "per_page": 100
        }
        
        response = requests.get(
            f"{self.api_base}/issues",
            headers=self.headers,
            params=params,
            timeout=15
        )
        
        if response.status_code != 200:
            return {"error": f"Failed to fetch issues: {response.status_code}"}
        
        issues = response.json()
        
        total = len(issues)
        completed = sum(1 for issue in issues if issue['state'] == 'closed')
        
        # Calculate average time to close
        close_times = []
        for issue in issues:
            if issue['state'] == 'closed' and issue['closed_at']:
                created = datetime.fromisoformat(issue['created_at'].replace('Z', '+00:00'))
                closed = datetime.fromisoformat(issue['closed_at'].replace('Z', '+00:00'))
                hours = (closed - created).total_seconds() / 3600
                close_times.append(hours)
        
        avg_time = sum(close_times) / len(close_times) if close_times else 0
        
        return {
            "total_digests": total,
            "completed_digests": completed,
            "completion_rate": (completed / total * 100) if total > 0 else 0,
            "avg_hours_to_close": round(avg_time, 1)
        }


def build_tracking_footer(issue_number: int, repo_owner: str, repo_name: str) -> str:
    """
    Build HTML footer with action tracking buttons.
    """
    issue_url = f"https://github.com/{repo_owner}/{repo_name}/issues/{issue_number}"
    
    footer_html = f'''
    <div style="background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 20px; margin-top: 30px;">
        <h3 style="margin-top: 0; color: #2c3e50;">Track Your Progress</h3>
        <p style="color: #6c757d; margin-bottom: 15px;">
            Use the buttons below to track actions and provide feedback on today's digest.
        </p>
        
        <div style="display: flex; gap: 10px; flex-wrap: wrap;">
            <a href="{issue_url}" 
               style="display: inline-block; background: #3498db; color: white; padding: 10px 20px; border-radius: 6px; text-decoration: none; font-weight: 500;">
                📋 View Tracking Issue
            </a>
            
            <a href="{issue_url}#new_comment_field" 
               style="display: inline-block; background: #2ecc71; color: white; padding: 10px 20px; border-radius: 6px; text-decoration: none; font-weight: 500;">
                ✅ Mark Actions Complete
            </a>
            
            <a href="{issue_url}#new_comment_field" 
               style="display: inline-block; background: #b45309; color: white; padding: 10px 20px; border-radius: 6px; text-decoration: none; font-weight: 500;">
                💬 Add Feedback
            </a>
        </div>
        
        <p style="color: #6c757d; font-size: 13px; margin-top: 15px; margin-bottom: 0;">
            Click any button to open the tracking issue in GitHub. Check off completed items, add comments, 
            or close the issue when you're done with today's digest.
        </p>
    </div>
    '''
    
    return footer_html
